"""
Django settings for imsuk project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q6*uidi1^$l$lf4^i13!d918)o65u_-_p1c7aye$iuygbk%5l5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'food',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'imsuk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'imsuk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [ BASE_DIR / 'food/static' ]


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'food.Customer'

TEMPLATES[0]['OPTIONS']['context_processors'] += [
    'food.context_processors.cart_context',
]

JAZZMIN_SETTINGS = {
    "site_title": "imsuk Admin",
    "site_header": "imsuk Admin",
    "site_brand": "imsuk",
    "site_logo": "images/imsuk-logo.svg", 
    "welcome_sign": "ยินดีต้อนรับสู่แผงควบคุม imsuk",
    "copyright": "© imsuk by itsareeee",

    # Layout
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],

    # Top Menu
    "topmenu_links": [
        {"name": "กลับหน้าเว็บ", "url": "/", "new_window": True},
    ],

    # Model Order (เรียงลำดับโมเดล)
    "order_with_respect_to": [
        "food.Allergen",
        "food.Restaurant",
        "food.MenuItem",
        "food.CartItem",
        "food.OrderItem",
        "food.Order",
    ],

    # App Icons
    "icons": {
        "food.Allergen": "fas fa-allergies",
        "food.Restaurant": "fas fa-store",
        "food.MenuItem": "fas fa-utensils",
        "food.CartItem": "fas fa-shopping-cart",
        "food.OrderItem": "fas fa-concierge-bell",
        "food.Order": "fas fa-receipt",
        "auth.User": "fas fa-user",
    },

    # Custom CSS
    "custom_css": "admin/custom.css",     # CSS จากข้อก่อนหน้า
    "theme": "default",
    "dark_mode_theme": "darkly",
}


JAZZMIN_UI_TWEAKS = {
    "theme": "default",
    "dark_mode_theme": "darkly",

    # สีสำหรับ nav link
    "accent": "green",  # ใช้กับปุ่มหลัก
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,

    "brand_colour": "navbar-green",  # Navbar
    "sidebar_nav_small_text": False,

    "sidebar_nav_child_indent": True,
    "sidebar_nav_flat_style": True,

    "custom_sidebar_links": {
        "Food": {
            "Allergens": "#f4c2ce",      # Azalea
            "Restaurants": "#f4c2ce",
            "Menu items": "#f4c2ce",

            "Cart items": "#bfd992",     # Deco
            "Order items": "#bfd992",
            "Orders": "#bfd992",
        }
    }
}